// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxiP2U9ReAzOWCAlJHTSaToPeUNAbH56A',
    appId: '1:24534206678:web:d3c67ba05963a95494a177',
    messagingSenderId: '24534206678',
    projectId: 'shopifyapp-c74a1',
    authDomain: 'shopifyapp-c74a1.firebaseapp.com',
    storageBucket: 'shopifyapp-c74a1.appspot.com',
    measurementId: 'G-49K9Q1BJXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQocy2p2ByOBPcmzuPf8zl1wwdx9pdlJw',
    appId: '1:24534206678:android:fe3fb3555063e24c94a177',
    messagingSenderId: '24534206678',
    projectId: 'shopifyapp-c74a1',
    storageBucket: 'shopifyapp-c74a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAs3eAk0togAGVhP6pQJiQV9bvWfAODJY',
    appId: '1:24534206678:ios:8eb3a1c91125be6294a177',
    messagingSenderId: '24534206678',
    projectId: 'shopifyapp-c74a1',
    storageBucket: 'shopifyapp-c74a1.appspot.com',
    iosBundleId: 'com.example.shopifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAs3eAk0togAGVhP6pQJiQV9bvWfAODJY',
    appId: '1:24534206678:ios:fadf5bbade3163d394a177',
    messagingSenderId: '24534206678',
    projectId: 'shopifyapp-c74a1',
    storageBucket: 'shopifyapp-c74a1.appspot.com',
    iosBundleId: 'com.example.shopifyApp.RunnerTests',
  );
}
